name: run-bot

on:
  schedule:
    - cron: '*/30 * * * *'  # roda a cada 30 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar bot
        run: python bot.py

      - name: Confirmar branch
        run: git checkout main

      - name: Configurar Git para commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit e push do histórico
        run: |
          git add ultimo_estado.txt
          git commit -m "update estado" || echo "Sem alterações para commitar"
          git push origin main
