name: run-bot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: 'latest'

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar bot
        run: python bot.py

      - name: Commit e push do histórico
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ultimo_estado.txt
          git commit -m "update estado" || echo "Sem alterações para commitar"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/renata-bot/Bot-Vagas-Periodico.git
