name: run-bot

on:
  schedule:
    - cron: '*/30 * * * *'  # roda a cada 30 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true

      - name: Detectar versão do Google Chrome
        id: chrome_version
        run: |
          echo "CHROME_VERSION=$(google-chrome --version | grep -oP '\\d+\\.\\d+\\.\\d+')" >> $GITHUB_ENV

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: ${{ env.CHROME_VERSION }}

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium  # só se seu bot precisar de selenium

      - name: Rodar bot
        run: python bot.py

      - name: Configurar Git para commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit e push do histórico
        run: |
          git add ultimo_estado.txt
          git commit -m "update estado" || echo "Sem alterações para commitar"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/renata-bot/Bot-Vagas-Periodico.git
